/run/initialize

/gps/particle neutron
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/radius 4.75
/gps/ang/type iso

/gps/ene/type Arb
/gps/hist/type arb

/gps/hist/point 0.25 0.0519
/gps/hist/point 0.5 0.081
/gps/hist/point 0.75 0.0886
/gps/hist/point 1.0 0.0883
/gps/hist/point 1.25 0.084
/gps/hist/point 1.5 0.0778
/gps/hist/point 1.75 0.707
/gps/hist/point 2.0 0.0633
/gps/hist/point 2.25 0.0562
/gps/hist/point 2.5 0.0494
/gps/hist/point 2.75 0.0431
/gps/hist/point 3.0 0.0375
/gps/hist/point 3.25 0.0324
/gps/hist/point 3.5 0.0278
/gps/hist/point 3.75 0.0238
/gps/hist/point 4.0 0.0204 
/gps/hist/point 4.25 0.0173
/gps/hist/point 4.5 0.0147
/gps/hist/point 4.75 0.0125
/gps/hist/point 5.0 0.0105 
/gps/hist/point 5.25 0.0089
/gps/hist/point 5.5 0.00747 
/gps/hist/point 5.75 0.0628
/gps/hist/point 6.0 0.00526
/gps/hist/point 6.25 0.0044
/gps/hist/point 6.5 0.00368 
/gps/hist/point 6.75 0.00306
/gps/hist/point 7.0 0.00256
/gps/hist/point 7.25 0.0021
/gps/hist/point 7.5 0.00178
/gps/hist/point 7.75 0.00148
/gps/hist/point 8.0 0.0012
/gps/hist/point 8.25 0.0010  
/gps/hist/point 8.5 0.0008
/gps/hist/point 8.75 0.0007
/gps/hist/point 9.0 0.0006



/gps/hist/inter Lin

/gps/verbose 1
  
/run/beamOn 10
